### ISSUE TITLE
make Sphinx dependency optional

### ISSUE THREAD

**Issue by carlotardivo** [thclark/rstcloth#30]
Currently Sphinx dependency is not optional. I read the [current comment](https://github.com/thclark/rstcloth/blob/a3678e24a84af36c1a5b8267b0b76068e7f5f1d5/pyproject.toml#L33) the redirects to [this poetry issue](https://github.com/python-poetry/poetry/issues/3348), but now it is closed, and maybe the problem has been fixed. 

In any case I think that the current `sphinx = ">=2,<5"` dependency should 
* be moved under dev section 
* or at least be optional
* or at least updated to `sphinx = ">=2"` (is there any reason why the current 5 version is not ok?).

Currently this library cannot be used in a project with the currently latest Sphinx version (5.1.1)

**Comment by thclark** [comment]
Hi @carlotardivo this is a bit confusing. 

> Currently this library cannot be used in a project with the currently latest Sphinx version (5.1.1)

I suspect that this is *actually* what you're trying to do, in which case making sphinx optional isn't the correct way of doing it. Can you clarify which of the following you're trying to do:

1. install on a system where you DON'T want to install sphinx at the same time, and use rstcloth totally independently, or 
2. install on a system where you DO want sphinx at the same time, but want to use sphinx >=5?

If it's (1) can you make a use case for why you'd do that? I can see that you might want to just create `.rst` files for later rendering by a separate application (or use a rendering engine other than sphinx) but I think that'd be rare so I don't want to commit to supporting it unless I'm clear that there's a need for it (if there is a real need, then we can look into how to do that, I can't remember if we actually import sphinx anywhere, but that would need to be checked before supporting this feature).

If it's (2) then it's simply a case of widening the sphinx version range to `sphinx = ">=2,<6" and adding sphinx 6 to the tox test matrix to make sure it works (to answer your question, I'm not aware of any reason it shouldn't work, but responsible management of a library demands that we actually test it before opening up the compatibility range.

Finally, can you clarify how moving it to the `dev` section would be useful? Is it just because that would be a workaround to the version range?

**Comment by carlotardivo** [comment]
Hi @thclark, thanks for the response.

I'm currently on the situation (2). I have a project with the latest Sphinx version (>=5) installed, and for that reason in that environment I cannot install the RstCloth library. And yes, I was suggesting to move the sphinx dependency to the `dev` section just as a workaround to this (but I clearly was assuming that sphinx is actually a dev dependency).
